### ISSUE TITLE
Oh... 拼写错误？

### ISSUE THREAD

**Issue by lhy0403** [micromaomao/maowtm.org#2]
https://maowtm.org/Programming_Skills/
![default](https://user-images.githubusercontent.com/18734999/35787015-1ede08d2-0a66-11e8-8454-ccef4392f877.png)
you made it yourself or just an accident?
"Terminal"

**Comment by micromaomao** [comment]
Fixed (71bffe3386e26c753b23c606489af66e93014a4a), thanks a lot! These files were not spellchecked after they are written…
